.TH "deprecated" 3 "Version v1.0" "RedisX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP

.IP "\fBGlobal \fBredisxSetTLSCiphers\fP (\fBRedis\fP *redis, const char *cipher_list)\fP" 1c
For OpenSSL >= 1\&.1\&.1, \fC\fBredisxSetTLSCipherSuites()\fP\fP should be used instead\&. 
.PP

