.TH "RedisClient" 3 "Version v0.9" "RedisX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RedisClient \- Structure that represents a single \fBRedis\fP client connection instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <redisx\&.h>\fP
.SH "Detailed Description"
.PP 
Structure that represents a single \fBRedis\fP client connection instance\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RedisX from the source code\&.
