.TH "RedisEntry" 3 "Version v1.0" "RedisX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RedisEntry \- A single key / value entry, or field, in the \fBRedis\fP database\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <redisx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.RI "The \fBRedis\fP key or field name\&. "
.ti -1c
.RI "int \fBlength\fP"
.br
.RI "Bytes in value\&. "
.ti -1c
.RI "char * \fBvalue\fP"
.br
.RI "The string value stored for that field\&. "
.in -1c
.SH "Detailed Description"
.PP 
A single key / value entry, or field, in the \fBRedis\fP database\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RedisX from the source code\&.
