.TH "RedisMap" 3 "Version v0.9" "RedisX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RedisMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <redisx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRESP\fP * \fBkey\fP"
.br
.RI "The keyword component\&. "
.ti -1c
.RI "\fBRESP\fP * \fBvalue\fP"
.br
.RI "The associated value component\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure that represents a key/value mapping in RESP3\&.
.PP
\fBSee also\fP
.RS 4
\fBredisxIsMapType()\fP 
.PP
\fBRESP3_MAP\fP 
.PP
\fBRESP3_ATTRIBUTE\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for RedisX from the source code\&.
