.TH "RedisCluster" 3 "Version v0.9" "RedisX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RedisCluster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <redisx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBpriv\fP"
.br
.RI "Private data not exposed to users\&. "
.in -1c
.SH "Detailed Description"
.PP 
A \fBRedis\fP cluster configuration 

.SH "Author"
.PP 
Generated automatically by Doxygen for RedisX from the source code\&.
