.TH "RESP" 3 "Version v0.9" "RedisX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RESP \- Structure that represents a \fBRedis\fP response (\fBRESP\fP format)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <redisx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "enum \fBresp_type\fP \fBtype\fP"
.br
.RI "\fBRESP\fP type; RESP_ARRAY, RESP_INT \&.\&.\&. "
.ti -1c
.RI "void * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that represents a \fBRedis\fP response (\fBRESP\fP format)\&. 

REFERENCES: 
.PD 0
.IP "1." 4
https://github.com/redis/redis-specifications/tree/master/protocol 
.PP
.PP
\fBSee also\fP
.RS 4
\fBredisxDestroyRESP()\fP 
.PP
\fBredisxIsScalarType()\fP 
.PP
\fBredisxIsStringType()\fP 
.PP
\fBredisxIsArrayType()\fP 
.PP
\fBredisxIsMapType()\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "int n"
Either the integer value of a RESP_INT or a RESP3_BOOLEAN response, or the dimension of the value field\&. 
.SS "void* value"
Pointer to text (char *) content or to an array of components (RESP**) or (\fBRedisMapEntry\fP *), or else a pointer to a \fCdouble\fP, depending on \fCtype\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RedisX from the source code\&.
