name: Static Analysis

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '*.mk'
      - '.github/workflows/analyze.yml'

  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '*.mk'
      - '.github/workflows/analyze.yml'

jobs:

  cppcheck:
    name: Check source code

    runs-on: ubuntu-latest
    env:
      CC: gcc
      XCHANGE: xchange
    steps:

    - name: Check out RedisX
      uses: actions/checkout@v4

    - name: Check out xchange
      uses: actions/checkout@v4
      with:
        repository: Smithsonian/xchange
        path: xchange

    - name: install dependencies
      run: sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: make analyze
