name: API documentation
permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [published]

  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'include/**'
      - 'css/**'
      - 'resources/**'
      - 'Doxyfile'
      - '*.md'
      - '.github/workflows/dox.yml'

  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'css/**'
      - 'resources/**'
      - 'Doxyfile'
      - '*.md'
      - '.github/workflows/dox.yml'

jobs:

  apidocs:
    name: Generate API documentation

    runs-on: ubuntu-latest
    steps:

    - name: install doxygen
      run: sudo apt-get install doxygen

    - name: Check out RedisX
      uses: actions/checkout@v4

    - name: Generate docs
      run: make local-dox

  site-update:
    name: Update github pages
    needs: apidocs
    if: github.repository_owner == 'Smithsonian' && (github.event_name == 'release' || contains(github.event.head_commit.message, 'site update'))

    runs-on: ubuntu-latest
    steps:

    - name: install doxygen
      run: sudo apt-get install doxygen

    - name: Checkout source
      uses: actions/checkout@v4
      with:
        repository: Smithsonian/redisx
        path: redisx

    - name: Check out xchange
      uses: actions/checkout@v4
      with:
        repository: Smithsonian/xchange
        path: xchange

    - name: Generate docs
      run: make -C xchange local-dox

    - name: Generate headless README for RedisX
      run: make -C redisx README-redisx.md

    - name: Generate RedisX apidocs
      uses: mattnotmitt/doxygen-action@v1.9.8
      with:
        additional-packages: font-roboto
        working-directory: ./redisx

    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: 'gh-pages'
        path: site

    - name: Assert site/doc/
      run: mkdir -p site/doc

    - name: Copy README
      run: |
        echo '<img src="/redisx/resources/CfA-logo.png" alt="CfA logo" width="400" height="67" align="right">' > site/doc/README.md
        echo '<br clear="all">' >> site/doc/README.md
        cat redisx/README-redisx.md >> site/doc/README.md

    - name: Copy CHANGELOG
      run: cp redisx/CHANGELOG.md site/doc/

    - name: Copy API documentation
      run: cp -a redisx/apidoc site/

    - name: Push to pages
      run: |
        cd site
        git config --global user.email "$GITHUB_JOB+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
        git add -A
        git commit -m "[automated site update]" && git push || true

  changelog-update:
    name: Update CHANGELOG on github pages
    if: github.repository_owner == 'Smithsonian' && contains(github.event.head_commit.message, 'changelog update')

    runs-on: ubuntu-latest
    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: 'gh-pages'
        path: site

    - name: Assert site/doc/
      run: mkdir -p site/doc

    - name: Copy CHANGELOG
      run: cp CHANGELOG.md site/doc/

    - name: Push to pages
      run: |
        cd site
        git config --global user.email "$GITHUB_JOB+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
        git add -A
        git commit -m "[automated site update]" && git push || true
